package com.m2f.template.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class TerminalColors(
    val bg: Color,
    val surface: Color,
    val accent: Color,
    val accentMuted: Color,
    val text: Color,
    val textMuted: Color,
    val textDim: Color,
    val border: Color,
    val inset: Color,
    val success: Color,
    val successBg: Color,
    val warning: Color,
    val warningBg: Color,
    val error: Color,
    val errorBg: Color,
    val info: Color,
    val infoBg: Color,
    // Button tokens
    val btnPrimaryBg: Color,
    val btnPrimaryText: Color,
    val btnPrimaryHoverBg: Color,
    val btnSecondaryBg: Color,
    val btnSecondaryText: Color,
    val btnSecondaryBorder: Color,
    val btnSecondaryHoverBg: Color,
    val btnGhostText: Color,
    val btnGhostHoverBg: Color,
    val btnDestructiveBg: Color,
    val btnDestructiveText: Color,
    val btnDestructiveHoverBg: Color,
    val btnSuccessBg: Color,
    val btnSuccessText: Color,
    val btnSuccessHoverBg: Color,
    val btnDisabledBg: Color,
    val btnDisabledText: Color,
    val btnDisabledBorder: Color,
    // Checkbox tokens
    val checkboxBg: Color,
    // Card accent tokens
    val cardAccentBg: Color,
    val cardAccentHeaderBg: Color,
    val cardAccentHeaderText: Color,
    val cardAccentBodyText: Color,
    // Table tokens
    val tableHeaderBg: Color,
    val tableHeaderText: Color,
    val tableRowTextPrimary: Color,
    val tableRowTextSecondary: Color,
    val tableRowSelectedBg: Color,
)

val LocalTerminalColors = staticCompositionLocalOf {
    TerminalColors(
        bg = Color.Unspecified,
        surface = Color.Unspecified,
        accent = Color.Unspecified,
        accentMuted = Color.Unspecified,
        text = Color.Unspecified,
        textMuted = Color.Unspecified,
        textDim = Color.Unspecified,
        border = Color.Unspecified,
        inset = Color.Unspecified,
        success = Color.Unspecified,
        successBg = Color.Unspecified,
        warning = Color.Unspecified,
        warningBg = Color.Unspecified,
        error = Color.Unspecified,
        errorBg = Color.Unspecified,
        info = Color.Unspecified,
        infoBg = Color.Unspecified,
        btnPrimaryBg = Color.Unspecified,
        btnPrimaryText = Color.Unspecified,
        btnPrimaryHoverBg = Color.Unspecified,
        btnSecondaryBg = Color.Unspecified,
        btnSecondaryText = Color.Unspecified,
        btnSecondaryBorder = Color.Unspecified,
        btnSecondaryHoverBg = Color.Unspecified,
        btnGhostText = Color.Unspecified,
        btnGhostHoverBg = Color.Unspecified,
        btnDestructiveBg = Color.Unspecified,
        btnDestructiveText = Color.Unspecified,
        btnDestructiveHoverBg = Color.Unspecified,
        btnSuccessBg = Color.Unspecified,
        btnSuccessText = Color.Unspecified,
        btnSuccessHoverBg = Color.Unspecified,
        btnDisabledBg = Color.Unspecified,
        btnDisabledText = Color.Unspecified,
        btnDisabledBorder = Color.Unspecified,
        checkboxBg = Color.Unspecified,
        cardAccentBg = Color.Unspecified,
        cardAccentHeaderBg = Color.Unspecified,
        cardAccentHeaderText = Color.Unspecified,
        cardAccentBodyText = Color.Unspecified,
        tableHeaderBg = Color.Unspecified,
        tableHeaderText = Color.Unspecified,
        tableRowTextPrimary = Color.Unspecified,
        tableRowTextSecondary = Color.Unspecified,
        tableRowSelectedBg = Color.Unspecified,
    )
}

// Light theme -- extracted from terminal_design_system.pen variables
val TerminalLightColors = TerminalColors(
    bg = Color(0xFFE8E8E8),
    surface = Color(0xFFF5F5F5),
    accent = Color(0xFF525252),
    accentMuted = Color(0xFFE5E5E5),
    text = Color(0xFF1F1F1F),
    textMuted = Color(0xFF5A5A5A),
    textDim = Color(0xFF787878),
    border = Color(0xFFD0D0D0),
    inset = Color(0xFFEFEFEF),
    success = Color(0xFF4A9B6E),
    successBg = Color(0xFFD8E8DE),
    warning = Color(0xFFA08840),
    warningBg = Color(0xFFEDE8D8),
    error = Color(0xFFB05A5A),
    errorBg = Color(0xFFEDDCDC),
    info = Color(0xFF4A7EB0),
    infoBg = Color(0xFFDCE6EF),
    btnPrimaryBg = Color(0xFF525252),
    btnPrimaryText = Color(0xFFFAFAFA),
    btnPrimaryHoverBg = Color(0xFF3A3A3A),
    btnSecondaryBg = Color(0xFFFFFFFF),
    btnSecondaryText = Color(0xFF171717),
    btnSecondaryBorder = Color(0xFFD4D4D4),
    btnSecondaryHoverBg = Color(0xFFF5F5F5),
    btnGhostText = Color(0xFF525252),
    btnGhostHoverBg = Color(0xFFF5F5F5),
    btnDestructiveBg = Color(0xFFF0E8E8),
    btnDestructiveText = Color(0xFF9A4444),
    btnDestructiveHoverBg = Color(0xFFE8DADA),
    btnSuccessBg = Color(0xFFE8F0EA),
    btnSuccessText = Color(0xFF3D7A4A),
    btnSuccessHoverBg = Color(0xFFD8E8DE),
    btnDisabledBg = Color(0xFFF5F5F5),
    btnDisabledText = Color(0xFFA3A3A3),
    btnDisabledBorder = Color(0xFFE5E5E5),
    checkboxBg = Color(0xFFF5F5F5),
    cardAccentBg = Color(0xFFE5E5E5),
    cardAccentHeaderBg = Color(0xFF525252),
    cardAccentHeaderText = Color(0xFFE8EBE4),
    cardAccentBodyText = Color(0xFF525252),
    tableHeaderBg = Color(0xFFE5E5E5),
    tableHeaderText = Color(0xFF525252),
    tableRowTextPrimary = Color(0xFF171717),
    tableRowTextSecondary = Color(0xFF525252),
    tableRowSelectedBg = Color(0xFFEDF2EE),
)

// Dark theme -- extracted from terminal_design_system.pen variables
val TerminalDarkColors = TerminalColors(
    bg = Color(0xFF101012),
    surface = Color(0xFF1A1A1C),
    accent = Color(0xFFA3A3A3),
    accentMuted = Color(0xFF262626),
    text = Color(0xFFD4D4D4),
    textMuted = Color(0xFF8A8A8A),
    textDim = Color(0xFF5A5A5A),
    border = Color(0xFF2A2A2E),
    inset = Color(0xFF212124),
    success = Color(0xFF6BAF8A),
    successBg = Color(0xFF1A2820),
    warning = Color(0xFFC4A860),
    warningBg = Color(0xFF28241A),
    error = Color(0xFFCA7A7A),
    errorBg = Color(0xFF2A1A1A),
    info = Color(0xFF7AA4CA),
    infoBg = Color(0xFF1A2530),
    btnPrimaryBg = Color(0xFFD4D4D4),
    btnPrimaryText = Color(0xFF171717),
    btnPrimaryHoverBg = Color(0xFFE5E5E5),
    btnSecondaryBg = Color(0xFF171717),
    btnSecondaryText = Color(0xFFE5E5E5),
    btnSecondaryBorder = Color(0xFF333333),
    btnSecondaryHoverBg = Color(0xFF262626),
    btnGhostText = Color(0xFFA3A3A3),
    btnGhostHoverBg = Color(0xFF262626),
    btnDestructiveBg = Color(0xFF251A1A),
    btnDestructiveText = Color(0xFFC06060),
    btnDestructiveHoverBg = Color(0xFF301F1F),
    btnSuccessBg = Color(0xFF1A231C),
    btnSuccessText = Color(0xFF5A9E6A),
    btnSuccessHoverBg = Color(0xFF1F3028),
    btnDisabledBg = Color(0xFF1C1C1C),
    btnDisabledText = Color(0xFF525252),
    btnDisabledBorder = Color(0xFF2A2A2A),
    checkboxBg = Color(0xFF262626),
    cardAccentBg = Color(0xFF262626),
    cardAccentHeaderBg = Color(0xFFD4D4D4),
    cardAccentHeaderText = Color(0xFF171717),
    cardAccentBodyText = Color(0xFFA3A3A3),
    tableHeaderBg = Color(0xFF1F1F1F),
    tableHeaderText = Color(0xFFA3A3A3),
    tableRowTextPrimary = Color(0xFFE5E5E5),
    tableRowTextSecondary = Color(0xFFA3A3A3),
    tableRowSelectedBg = Color(0xFF1A231C),
)
